spring:
  application:
    name: video-manager-api
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5434/video_db}
    username: ${DB_USERNAME:fiapx}
    password: ${DB_PASSWORD:fiapx}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

app:
  security:
    jwt-secret: ${JWT_SECRET:local-development-jwt-secret-change-me-1234567890}
    jwt-issuer: ${JWT_ISSUER:customer-auth-api}

server:
  port: ${SERVER_PORT:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
