apiVersion: v1
kind: ConfigMap
metadata:
  name: video-manager-api
  namespace: ${apps_namespace}
data:
  DB_URL: jdbc:postgresql://postgres-video.data-plataform.svc.cluster.local:5432/video_db
  KAFKA_BOOTSTRAP_SERVERS: kafka.data-plataform.svc.cluster.local:9092
  MINIO_ENDPOINT: ${s3_endpoint}
  MINIO_INPUT_BUCKET: ${s3_input_bucket_name}
  MINIO_OUTPUT_BUCKET: ${s3_output_bucket_name}
  CUSTOMER_AUTH_API_URL: http://customer-auth-api.${apps_namespace}.svc.cluster.local:8081
