apiVersion: v1
kind: ConfigMap
metadata:
  name: video-manager-api
  namespace: ${apps_namespace}
data:
  DB_URL: jdbc:postgresql://postgres-video.data-plataform.svc.cluster.local:5432/video_db
  KAFKA_BOOTSTRAP_SERVERS: kafka.data-plataform.svc.cluster.local:9092
  MINIO_ENDPOINT: ${s3_endpoint}
  MINIO_INPUT_BUCKET: ${s3_input_bucket_name}
  MINIO_OUTPUT_BUCKET: ${s3_output_bucket_name}
  CUSTOMER_AUTH_API_URL: http://customer-auth-api.${apps_namespace}.svc.cluster.local:8081
  PUBLIC_API_BASE_URL: ${public_api_base_url}
  MAIL_HOST: ${mail_host}
  MAIL_PORT: "${mail_port}"
  MAIL_SMTP_AUTH: "true"
  MAIL_SMTP_STARTTLS_ENABLE: "true"
  NOTIFICATION_EMAIL_FROM: ${notification_email_from}
  OTEL_SERVICE_NAME: video-manager-api
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_TRACES_EXPORT_ENABLED: "true"
  OTEL_METRICS_EXPORTER: "none"
  OTEL_LOGS_EXPORTER: "none"
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://jaeger.observability.svc.cluster.local:4318/v1/traces"
  OTEL_EXPORTER_OTLP_TRACES_PROTOCOL: "http/protobuf"
  TRACING_SAMPLING_PROBABILITY: "1.0"
