apiVersion: v1
kind: Secret
metadata:
  name: video-manager-api
  namespace: ${apps_namespace}
type: Opaque
stringData:
  DB_PASSWORD: ${postgres_password}
  JWT_SECRET: ${jwt_secret}
  INTERNAL_API_KEY: ${internal_api_key}
  MINIO_ACCESS_KEY: ${s3_access_key}
  MINIO_SECRET_KEY: ${s3_secret_key}
  MAIL_USERNAME: ${mail_username}
  MAIL_PASSWORD: ${mail_password}
